name: sis_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-107.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: any
  shared_preferences: ^2.0.0
  http: ^1.2.2
  ini: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/sis_logo.jpg
    - assets/images/sis_map.jpg
    - assets/cfg/env.ini